#version 430
layout(local_size_x = 1) in;

struct Point {
    vec3 pos;
    vec3 color;
};

layout(std430, binding = 1) buffer PointsBuffer {
    Point[] pointsArr;
};

void main() {
    uint i = gl_GlobalInvocationID.x;

    // Increment the X component of the position
    pointsArr[i].pos *= 0.99;
    pointsArr[i].color *= 0.99;

    // Optionally, you can use integer values
    // pointsArr[i].pos.x += 1;
}
